const sol = document.getElementById('sol')
const arbol = document.getElementById('arbol')
const lagartija = document.getElementById('lagartija')
const vaca = document.getElementById('vaca')
const pez = document.getElementById('pez')
const cangrejo = document.getElementById('cangrejo')
const escorpion = document.getElementById('escorpion')
const tortuga = document.getElementById('tortuga')
const vibora = document.getElementById('vibora')

sol.onclick = (e) => document.getElementById('sol-audio').play()
arbol.onclick = (e) => document.getElementById('arbol-audio').play()
lagartija.onclick = (e) => document.getElementById('lagartija-audio').play()
vaca.onclick = (e) => document.getElementById('vaca-audio').play()
pez.onclick = (e) => document.getElementById('pez-audio').play()
cangrejo.onclick = (e) => document.getElementById('cangrejo-audio').play()
escorpion.onclick = (e) => document.getElementById('escorpion-audio').play()
tortuga.onclick = (e) => document.getElementById('tortuga-audio').play()
vibora.onclick = (e) => document.getElementById('vibora-audio').play()

